repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
        files: "\\.py$"
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black (repo formatting)
        language_version: python3
        files: "\\.py$"
